GET http://127.0.0.1:5000/operacao HTTP/1.1

###

POST http://127.0.0.1:5000/operacao HTTP/1.1
content-type: application/json

{
    "datahora": "2023-10-07 09:30:00.0",
    "periodo": "semanal",
    "tipo": "despesa",
    "categoria": "conta",
    "valor": 200,
    "usuario": "tkautzmann"
}